import React from 'react';
import { HiShieldExclamation, HiUserGroup } from 'react-icons/hi2';
import { useApp } from '../context/AppContext';

export const DisclaimerView = () => {
  const { openFacilitatorModal } = useApp();

  const SECTIONS = [
    {
      title: '1. Nature of the Service',
      body: 'AyurPedia is an educational and decision-support artificial intelligence platform designed to assist Ayurvedic researchers, pharmaceutical enterprises, and practitioners in understanding intellectual property frameworks (including the Indian Patents Act 1970, Section 3(p), the Biological Diversity Act 2002, FSSAI Ayurveda-Aahar Regulations 2022, and the WIPO GRATK Treaty 2024).',
    },
    {
      title: '2. No Legal or Professional Attorney-Client Relationship',
      body: 'Use of AyurPedia, interactions with the chat assistant, and results from the formulation classification engine do not establish an attorney-client relationship. Outputs are generated by machine-learning models grounded on statutory text and should not be treated as formal patent validity certifications or binding regulatory approvals.',
    },
    {
      title: '3. Verification Requirement',
      body: 'Users are strongly advised to corroborate citations with official gazette notifications, the Traditional Knowledge Digital Library (TKDL), the Controller General of Patents, Designs and Trade Marks (CGPDTM), or a registered patent attorney before filing commercial applications or product licenses.',
    },
  ];

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="bg-[#fffdf8] dark:bg-primary-950/40 rounded-3xl p-8 border border-stone-200/80 dark:border-primary-900/50 shadow-card space-y-6">
        <div className="flex items-center gap-3 border-b border-stone-200 dark:border-primary-900/50 pb-5">
          <div className="p-2.5 bg-accent-100 dark:bg-accent-500/15 text-accent-700 dark:text-accent-300 rounded-2xl">
            <HiShieldExclamation className="w-8 h-8" />
          </div>
          <div>
            <h1 className="text-2xl font-serif font-semibold text-stone-900 dark:text-stone-100">Legal &amp; Regulatory Disclaimer</h1>
            <p className="text-xs text-stone-500 dark:text-stone-400 mt-0.5">Notice on AI-Assisted Ayurvedic Knowledge &amp; IPR Analysis</p>
          </div>
        </div>

        <div className="space-y-6 text-sm text-stone-700 dark:text-stone-300 leading-relaxed">
          {SECTIONS.map((s, i) => (
            <section key={i} className="space-y-1.5">
              <h2 className="text-base font-serif font-semibold text-stone-900 dark:text-stone-100">{s.title}</h2>
              <p>{s.body}</p>
            </section>
          ))}

          <div className="p-5 bg-primary-50 dark:bg-primary-900/30 rounded-2xl border border-primary-200/70 dark:border-primary-800/50 flex flex-col sm:flex-row items-center justify-between gap-4 mt-2">
            <div>
              <h3 className="font-serif font-semibold text-primary-900 dark:text-stone-100">Need Professional Assistance?</h3>
              <p className="text-xs text-primary-800 dark:text-stone-400 mt-0.5">
                Connect with our network of human legal facilitators specializing in Ayurvedic and herbal IPR.
              </p>
            </div>
            <button
              type="button"
              onClick={() => openFacilitatorModal()}
              className="inline-flex items-center gap-2 px-5 py-2.5 btn-premium text-white font-bold text-xs rounded-xl transition-all shrink-0 cursor-pointer"
            >
              <HiUserGroup className="w-4 h-4 text-accent-300" />
              <span>Contact Facilitator</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerView;
