import React from 'react';
import { HiShieldExclamation, HiCheckCircle, HiUserGroup } from 'react-icons/hi2';
import { useApp } from '../context/AppContext';

export const DisclaimerView = () => {
  const { openFacilitatorModal } = useApp();

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white rounded-3xl p-8 border border-stone-200 shadow-glass space-y-6">
        <div className="flex items-center gap-3 border-b border-stone-200 pb-4">
          <div className="p-2.5 bg-amber-100 text-amber-800 rounded-2xl">
            <HiShieldExclamation className="w-8 h-8" />
          </div>
          <div>
            <h1 className="text-2xl font-black text-stone-900">Legal & Regulatory Disclaimer</h1>
            <p className="text-xs text-stone-500">Notice on AI-Assisted Ayurvedic Knowledge & IPR Analysis</p>
          </div>
        </div>

        <div className="space-y-4 text-xs sm:text-sm text-stone-700 leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-base font-bold text-stone-900">1. Nature of the Service</h2>
            <p>
              AyurPedia is an educational and decision-support artificial intelligence platform designed to assist Ayurvedic researchers, pharmaceutical enterprises, and practitioners in understanding intellectual property frameworks (including Indian Patents Act 1970, Section 3(p), the Biological Diversity Act 2002, FSSAI Ayurveda-Aahar Regulations 2022, and the WIPO GRATK Treaty 2024).
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-stone-900">2. No Legal or Professional Attorney-Client Relationship</h2>
            <p>
              Use of AyurPedia, interactions with the chat assistant, and results from the formulation classification engine <strong>do not establish an attorney-client relationship</strong>. Outputs are generated by machine-learning models grounded on statutory text and should not be treated as formal patent validity certifications or binding regulatory approvals.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-base font-bold text-stone-900">3. Verification Requirement</h2>
            <p>
              Users are strongly advised to corroborate citations with official gazette notifications, the Traditional Knowledge Digital Library (TKDL) database, the Controller General of Patents, Designs and Trade Marks (CGPDTM), or consult a registered patent attorney before filing commercial applications or product licenses.
            </p>
          </section>

          <div className="p-4 bg-primary-50 rounded-2xl border border-primary-200 flex flex-col sm:flex-row items-center justify-between gap-4 mt-6">
            <div>
              <h3 className="font-bold text-primary-950 text-sm">Need Professional Assistance?</h3>
              <p className="text-xs text-primary-800 mt-0.5">
                Connect with our network of human legal facilitators specializing in Ayurvedic and herbal IPR.
              </p>
            </div>
            <button
              type="button"
              onClick={() => openFacilitatorModal()}
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary-700 hover:bg-primary-800 text-white font-bold text-xs rounded-xl shadow-xs transition-all shrink-0 cursor-pointer"
            >
              <HiUserGroup className="w-4 h-4" />
              <span>Contact Facilitator</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerView;
